#!/bin/bash
VERSION='node_exporter-1.3.1.linux-amd64'
SERVICENAME='node_exporter'

systemctl list-units --full -all | grep -Fq "$SERVICENAME.service"

sudo apt update 2>&1 apt.log
sudo apt -y upgrade 2>&1 apt.log

wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/$VERSION.tar.gz

tar xvzf $VERSION.tar.gz
cp $VERSION/node_exporter /usr/local/bin

useradd --no-create-home --shell /bin/false node_exporter
chown node_exporter:node_exporter /usr/local/bin/node_exporter

tee -a /etc/systemd/system/node_exporter.service  << EOF
[Unit]
Description=Node Exporter
Wants=network-online.target
After=network-online.target

[Service]
User=node_exporter
Group=node_exporter
Type=simple
ExecStart=/usr/local/bin/node_exporter
